[package]
name = "terra"
version = "0.1.0"
authors = ["jonathan"]

[[bin]]
name = "preview"
path = "src/preview.rs"

[dependencies]
piston_window = "0.67"
find_folder = "0.3.0"
image = "0.14"
piston2d-drag_controller = "0.19"
gfx = "0.16"
gfx_core = "0.7"
gfx_device_gl = "0.14"
vecmath = "0.3.0"
camera_controllers = "0.21"
pistoncore-sdl2_window = "0.43"
rand = "0.3"
shader_version = "0.2.1"
imagefmt = "4.0.0"
zip = "0.2"
safe-transmute = "0.3"
curl = {version = "0.4", optional = true}

[features]
default = ["download"]
download = ["curl"]
