[package]
name = "terra"
version = "0.2.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
license = "Apache-2.0"
description = "A rendering library for large scale terrains"
repository = "https://github.com/fintelia/terra"
homepage = "https://github.com/fintelia/terra"
documentation = "https://docs.rs/terra"
categories = ["game-engines", "rendering"]
readme = "README.md"
include = ["src/*", "rshader/*", "Cargo.toml", "README.md", "LICENSE", "screenshot.png"]

[[bin]]
name = "preview"
path = "src/preview.rs"
required-features = ["preview"]

[dependencies]
bincode = "0.8.0"
byteorder = "1.1.0"
cgmath = { version = "0.15", features = ["serde"] }
curl = "0.4"
gfx = "0.16"
gfx_core = "0.7"
image = "0.15"
lazy_static = "0.2"
lru-cache = "0.1.1"
memmap = "0.5.2"
notify = "4.0"
rand = "0.3"
rshader = { path = "rshader", features = [], version = "0.1.0" }
rustfft = "2.0.0"
safe-transmute = "0.3"
serde = "1.0"
serde_derive = "1.0"
shader_version = "0.2.1"
vec_map = "0.8"
vecmath = "0.3.0"
zip = "0.2"

# For preview
camera_controllers = {version = "0.21", optional = true}
piston_window = {version = "0.67", optional = true}

[features]
default = []
preview = ["piston_window", "camera_controllers"]
dynamic_shaders = ["rshader/dynamic_shaders"]

[profile.release]
debug=true

[workspace]
