[package]
name = "terra"
version = "0.3.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
license = "Apache-2.0"
description = "A rendering library for large scale terrains"
repository = "https://github.com/fintelia/terra"
homepage = "https://github.com/fintelia/terra"
documentation = "https://docs.rs/terra"
categories = ["game-engines", "rendering"]
readme = "README.md"
edition = "2018"

[dependencies]
rendy = { version = "0.3.1", features = ["vulkan"] }
winit = "0.19.1"
lazy_static = "1.3.0"
gfx-hal = "0.2.0"
env_logger = "0.6.1"
log = "0.4.6"
failure = "0.1.5"
serde = { version = "1.0.92", features = ["derive"] }
toml = "0.5.1"
memmap = "0.7.0"
petgraph = "0.4.13"
sha2 = "0.8.0"
bincode = "1.1.4"
generic-array = { version = "0.12", features = ["serde"] }
xdg = "2.2.0"
hex = "0.3.2"
open-location-code = "0.1.0"
serde_json = "1.0.40"
curl = "0.4.22"
safe-transmute = "0.10.1"
zip = "0.5.2"
shaderc = "0.5.0"
linked-hash-map = "0.5.2"
cgmath = "0.17.0"
collision = "0.20.1"
coord_transforms = "1.2.2"
nalgebra = "0.16.13"
vec_map = "0.8.1"
vecmath = "1.0.0"
astro = "2.0.0"
byteorder = "1.3.2"
zerocopy = "0.2.8"

amethyst = { version = "0.12.0", optional = true, features = ["vulkan", "gltf"] }
derivative = "1.0.2" # TODO: include for amethyst binary only.

# For preview
[dev-dependencies]

[features]
default = ["amethyst"]

[profile.release]
debug=true

[profile.dev]
opt-level = 1

[workspace]


[[bin]]
name = "amethyst"
path = "bin/amethyst.rs"
