[package]
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
categories = ["game-engines", "rendering"]
description = "A rendering library for large scale terrains"
documentation = "https://docs.rs/terra"
edition = "2018"
homepage = "https://github.com/fintelia/terra"
license = "Apache-2.0"
name = "terra"
readme = "README.md"
repository = "https://github.com/fintelia/terra"
version = "0.3.0"

[[bin]]
name = "preview"
path = "bin/preview.rs"

[dependencies]
anyhow = "1.0.36"
astro = "2.0.0"
bincode = "1.3.1"
bit-vec = "0.6.3"
bytemuck = "1.4.1"
byteorder = "1.3.4"
cgmath = { git = "https://github.com/rustgd/cgmath", rev = "8e0d5ece92ddccd1cbd9670b2bf3007ca9ada986", features = ["mint", "serde"] }
crossbeam = "0.8.0"
curl = "0.4.34"
dirs = "3.0.1"
futures = "0.3.8"
gilrs = "0.8.0"
image = "0.23.12"
lazy_static = "1.4.0"
linked-hash-map = "0.5.3"
log = "0.4.11"
lru-cache = "0.1.2"
lz4 = "1.23.2"
maplit = "1.0.2"
memmap = "0.7.0"
mint = "0.5.6"
num = "0.3.1"
open-location-code = "0.1.0"
pbr = { git = "https://github.com/fintelia/pb", rev = "7740234295184f84b4fbcd55c8c3fd5528b474ad" }
petgraph = "0.5.1"
rand = "0.8.0"
rand_distr = "0.4.0"
rayon = "1.5.0"
rshader = { path = "rshader", features = ["dynamic_shaders"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.60"
sha2 = "0.9.2"
sled = "0.34.6"
snap = "1.0.3"
structopt = "0.3.21"
thiserror = "1.0.22"
tiff = "=0.5.0"
tokio = { version = "1.0.0", features = ["fs", "macros", "sync", "rt", "rt-multi-thread", "io-util"] }
vec_map = { version = "0.8.2", features = ["serde"] }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "c0418b1b8ae22e86fd0e7a7eb486e04dcb0bd6f5" }
winit = "0.24.0"
zip = "0.5.9"

[dev-dependencies]
approx = "0.4.0"

[profile]
[profile.dev]
opt-level = 1

[profile.release]
debug = true
