[package]
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
categories = ["game-engines", "rendering"]
description = "A rendering library for large scale terrains"
documentation = "https://docs.rs/terra"
edition = "2021"
homepage = "https://github.com/fintelia/terra"
license = "Apache-2.0"
name = "terra"
readme = "README.md"
repository = "https://github.com/fintelia/terra"
version = "0.3.0"
resolver = "2"

[[bin]]
name = "preview"
path = "bin/preview.rs"

[dependencies]
anyhow = "1.0.58"
astro = "2.0.0"
atomicwrites = "0.3.1"
basis-universal = "0.2.0"
bincode = "1.3.3"
bytemuck = { version = "1.11.0", features = ["extern_crate_alloc"] }
byteorder = "1.4.3"
cgmath = { version = "0.18.0", features = ["mint", "serde"] }
chrono = "0.4.19"
cogbuilder = { path = "../cogbuilder" }
crossbeam = "0.8.2"
curl = "0.4.44"
dirs = "4.0.0"
env_logger = "0.9.0"
fnv = "1.0.7"
futures = "0.3.21"
gilrs = "0.9.0"
hyper = { version = "0.14.20", features = ["full"] }
hyper-tls = "0.5.0"
image = "0.24.3"
indicatif = "0.16.2"
itertools = "0.10.3"
lazy_static = "1.4.0"
linked-hash-map = "0.5.6"
log = "0.4.17"
lru = "0.7.8"
lz4 = "1.23.3"
maplit = "1.0.2"
memmap = "0.7.0"
mint = "0.5.9"
num = "0.4.0"
num-traits = "0.2.15"
open-location-code = "0.1.0"
planetcam = { path = "planetcam" }
quick-xml = { version = "0.23.0", features = ["serialize"] }
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.5.3"
rshader = { path = "rshader", features = ["dynamic_shaders"] }
rust-s3 = { version = "0.32.3", features = ["blocking", "tokio"] }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
sled = "0.34.7"
smaa = { version = "0.7.0", optional = true }
snap = "1.0.5"
sscanf = "0.3.1"
structopt = "0.3.26"
thiserror = "1.0.31"
tiff = "0.7.3"
tilefmt = { path = "tilefmt" }
tokio = { version = "1.20.1", features = ["fs", "macros", "sync", "rt", "rt-multi-thread", "io-util"] }
types = { path = "types" }
vec_map = { version = "0.8.2", features = ["serde"] }
vrt-file = { git = "https://github.com/fintelia/vrt-file", rev = "36b53590676eb7f6e42ea62279e2facd35249cfb" }
wgpu = { version = "0.13.1", features = ["spirv"] }
winit = "0.26.1"
zip = { version = "0.6.2", features = ["deflate"], default-features = false }

[dev-dependencies]
approx = "0.5.1"

[features]
trace = ["wgpu/trace"]
small-trace = ["trace"]
soft-float64 = []

[profile]
[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = true
incremental = true
