[package]
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
categories = ["game-engines", "rendering"]
description = "A rendering library for large scale terrains"
documentation = "https://docs.rs/terra"
edition = "2018"
homepage = "https://github.com/fintelia/terra"
license = "Apache-2.0"
name = "terra"
readme = "README.md"
repository = "https://github.com/fintelia/terra"
version = "0.3.0"

[[bin]]
name = "preview"
path = "bin/preview.rs"

[dependencies]
astro = "2.0.0"
bincode = "1.2.0"
bit-vec = "0.6.1"
byteorder = "1.3.2"
cgmath = { version = "0.17.0", features = ["mint"] }
collision = "0.20.1"
coord_transforms = { git = "https://github.com/fintelia/coord_transforms" }
curl = "0.4.25"
derivative = "1.0.3"
dirs = "2.0.2"
env_logger = "0.7.0"
failure = "0.1.6"
generic-array = { version = "0.12.3", features = ["serde"] }
glsl-layout = "0.3.2"
hex = "0.4.0"
image = { git = "https://github.com/fintelia/image", branch = "tiff-no-limit" }
lazy_static = "1.4.0"
linked-hash-map = "0.5.2"
log = "0.4.8"
lru-cache = "0.1.2"
memmap = "0.7.0"
mint = "0.5.4"
nalgebra = "0.18.1"
num = "0.2.0"
open-location-code = "0.1.0"
pbr = { git = "https://github.com/fintelia/pb", rev = "7740234295184f84b4fbcd55c8c3fd5528b474ad" }
petgraph = "0.4.13"
rand = "0.7.2"
rand_distr = "0.2.2"
rshader = { path = "rshader", features = ["dynamic_shaders"] }
safe-transmute = "0.10.1"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
sha2 = "0.8.0"
shred = { version = "0.9.3", features = ["nightly"] }
toml = "0.5.3"
vec_map = { version = "0.8.1", features = ["serde"] }
vecmath = "1.0.0"
wgpu = "0.5.0"
winit = "0.20.0-alpha5"
xdg = "2.2.0"
zerocopy = "0.2.8"
zip = "0.5.3"
bytemuck = "1.1.0"
wgpu_glyph = { git = "https://github.com/fintelia/wgpu_glyph", rev = "7c09d12815a1e3496418730172d293a16190c18f" }
futures = "0.3.1"
gilrs = "0.7.3"

[profile]
[profile.dev]
opt-level = 1

[profile.release]
debug = true
