[package]
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
categories = ["game-engines", "rendering"]
description = "A rendering library for large scale terrains"
documentation = "https://docs.rs/terra"
edition = "2018"
homepage = "https://github.com/fintelia/terra"
license = "Apache-2.0"
name = "terra"
readme = "README.md"
repository = "https://github.com/fintelia/terra"
version = "0.3.0"
[[bin]]
name = "amethyst"
path = "bin/amethyst.rs"

[dependencies]
astro = "2.0.0"
bincode = "1.2.0"
byteorder = "1.3.2"
cgmath = "0.17.0"
collision = "0.20.1"
curl = "0.4.25"
derivative = "1.0.3"
dirs = "2.0.2"
env_logger = "0.7.0"
failure = "0.1.6"
gfx-hal = "0.2.1"
glsl-layout = "0.3.2"
hex = "0.4.0"
image = { git = "https://github.com/image-rs/image", branch = "next" }
lazy_static = "1.4.0"
linked-hash-map = "0.5.2"
log = "0.4.8"
memmap = "0.7.0"
mint = "0.5.3"
nalgebra = "0.18.1"
num = "0.2.0"
open-location-code = "0.1.0"
pbr = { git = "https://github.com/fintelia/pb", rev = "7740234295184f84b4fbcd55c8c3fd5528b474ad" }
petgraph = "0.4.13"
safe-transmute = "0.10.1"
serde_json = "1.0.41"
sha2 = "0.8.0"
toml = "0.5.3"
vec_map = "0.8.1"
vecmath = "1.0.0"
winit = "0.19.3"
xdg = "2.2.0"
zerocopy = "0.2.8"
zip = "0.5.3"
bit-vec = "0.6.1"
lru-cache = "0.1.2"
rand_distr = "0.2.2"
rand = "0.7.2"
shred = { version = "0.9.3", features = ["nightly"] }

[dependencies.amethyst]
features = ["vulkan", "gltf"]
optional = true
version = "0.13.2"

[dependencies.coord_transforms]
git = "https://github.com/fintelia/coord_transforms"

[dependencies.generic-array]
features = ["serde"]
version = "0.12.3"

[dependencies.rendy]
features = ["vulkan"]
version = "0.3.2"

[dependencies.rshader]
features = ["dynamic_shaders"]
path = "rshader"

[dependencies.serde]
features = ["derive"]
version = "1.0.101"

[dependencies.shaderc]
features = ["build-from-source"]
version = "0.5.0"

[dev-dependencies]

[features]
default = ["amethyst"]

[profile]
[profile.dev]
opt-level = 1

[profile.release]
debug = true
