[package]
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
categories = ["game-engines", "rendering"]
description = "A rendering library for large scale terrains"
documentation = "https://docs.rs/terra"
edition = "2018"
homepage = "https://github.com/fintelia/terra"
license = "Apache-2.0"
name = "terra"
readme = "README.md"
repository = "https://github.com/fintelia/terra"
version = "0.3.0"

[[bin]]
name = "preview"
path = "bin/preview.rs"

[dependencies]
anyhow = "1.0.33"
astro = "2.0.0"
bincode = "1.3.1"
bit-vec = "0.6.2"
bytemuck = "1.4.1"
byteorder = "1.3.4"
cgmath = { version = "0.17.0", features = ["mint"] }
collision = "0.20.1"
coord_transforms = "1.3.0"
curl = "0.4.34"
derivative = "2.1.1"
dirs = "3.0.1"
env_logger = "0.8.1"
futures = "0.3.7"
generic-array = { version = "0.14.4", features = ["serde"] }
gilrs = "0.8.0"
glsl-layout = "0.3.2"
hex = "0.4.2"
image = "0.23.10"
lazy_static = "1.4.0"
linked-hash-map = "0.5.3"
log = "0.4.11"
lru-cache = "0.1.2"
maplit = "1.0.2"
memmap = "0.7.0"
mint = "0.5.5"
nalgebra = "0.21.1"
num = "0.3.0"
open-location-code = "0.1.0"
pbr = { git = "https://github.com/fintelia/pb", rev = "7740234295184f84b4fbcd55c8c3fd5528b474ad" }
petgraph = "0.5.1"
rand = "0.7.3"
rand_distr = "0.3.0"
rshader = { path = "rshader", features = ["dynamic_shaders"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
sha2 = "0.9.1"
shred = "0.10.2"
sled = "0.34.4"
tiff = "0.6.0"
toml = "0.5.7"
vec_map = { version = "0.8.2", features = ["serde"] }
vecmath = "1.0.0"
wgpu = "0.6.0"
winit = "0.23.0"
xdg = "2.2.0"
zerocopy = "0.3.0"
zip = "0.5.8"
thiserror = "1.0.21"
snap = "1.0.1"
structopt = "0.3.20"
rayon = "1.5.0"
flate2 = "1.0.14"
tokio = { version = "0.3.1", features = ["fs", "macros", "sync", "rt", "rt-multi-thread", "io-util"] }
approx = "0.4.0"
lz4 = "1.23.2"
itertools = "0.9.0"

[profile]
[profile.dev]
opt-level = 1

[profile.release]
debug = true
