center = "87JC9W00+"
side_length_sectors = 8

[nodes.3DEP_13]
projection = "NAD83"
resolution = 10812
format = "GridFloat+zip"
bib = "U.S. Geological Survey, 20181203, USGS NED 1/3 arc-second n38w081 1 x 1 degree GridFloat 2018: U.S. Geological Survey."
license = "Public Domain"
url = "https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/GridFloat/USGS_NED_13_{ns}{lat02}{ew}{long03}_GridFloat.zip"
# Example URL: https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/GridFloat/USGS_NED_13_n38w081_GridFloat.zip

[nodes.base_heights]
shader = "reproject_heights"
resolution = 257
kind = "heightmap"
format = "R32F"
inputs = { heights = "3DEP_13" }
corner_registration = true

[nodes.base_normals]
shader = "compute_normals"
resolution = 256
kind = "normalmap"
format = "Rgba8"
inputs = { heights = "base_heights" }

[shaders]
reproject_heights = '''
#version 450
void main() {
    /* TODO */
}
'''

compute_normals = '''
#version 450
void main() {
    /* TODO */
}
'''