[package]
name = "rshader"
version = "0.2.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
license = "Apache-2.0"
description = "A simply library for reloading shaders at runtime"
repository = "https://github.com/fintelia/terra"
homepage = "https://github.com/fintelia/terra"
categories = ["game-engines", "rendering"]

[dependencies]
failure = "0.1.1"
notify = "4.0"
shaderc = "0.5.0"
rendy = "0.3.2"

[features]
default = []
dynamic_shaders = []