[package]
name = "rshader"
version = "0.2.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
license = "Apache-2.0"
description = "A simply library for reloading shaders at runtime"
repository = "https://github.com/fintelia/terra"
homepage = "https://github.com/fintelia/terra"
categories = ["game-engines", "rendering"]
edition = "2018"

[dependencies]
failure = "0.1.6"
notify = "4.0.13"
shaderc = "0.6.1"
spirq = { git = "https://github.com/fintelia/spirq-rs", rev = "7b80ba366f9c8eb94450ba5d119dd6d8effa2dd5" }
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs", rev = "6ca03f8354db2e827b17d0af40c5c33083a15908" }

[features]
default = []
dynamic_shaders = []
