[package]
name = "rshader"
version = "0.1.0"
authors = ["Jonathan Behrens <fintelia@gmail.com>"]
license = "Apache-2.0"
description = "A simply library for reloading shaders at runtime"
repository = "https://github.com/fintelia/terra"
homepage = "https://github.com/fintelia/terra"
categories = ["game-engines", "rendering"]

[dependencies]
gfx = "0.16"
notify = "4.0"

[features]
default = []
dynamic_shaders = []